packages:
  - "examples/*"
  - "packages/*"
  - "apps/*"

catalog:
  "@goat-sdk/core": "^0.4.6"
  "zod": "^3.24.1"
  "tsup": "^8.0.2"
  "dotenv": "^16.4.5"
  "tsx": "^4.7.1"
  "typescript": "^5.3.3"
  "vitest": "^1.2.1"
  "@types/node": "^22.10.2"
  "@noble/curves": "^1.8.1"
  "@noble/hashes": "^1.7.1"
  "blakejs": "^1.2.1"
  "base64url": "^3.0.1"
  "@radixdlt/babylon-core-api-sdk": "^1.2.3"
  "@radixdlt/babylon-gateway-api-sdk": "^1.10.1"
  "@radixdlt/radix-dapp-toolkit": "^2.0.3"
  "@radixdlt/radix-engine-toolkit": "^1.0.5"
  "@radixdlt/rola": "^2.1.0"
  "neverthrow": "^8.0.0"
  "ed25519-hd-key": "^1.3.0"
  "bip39": "^3.1.0"
  "effect": "^3.14.1"
  '@effect/platform': ^0.94.1
  '@effect/platform-node': ^0.104.0
  'bignumber.js': '^9.2.1'
  "fetch-retry": "^6.0.0"
  "undici": "^7.15.0"
  "@effect/vitest": "^0.25.1"
  "tsdown": "^0.15.12"