import s from "sbor-ez-mode";

// Generated TypeScript schema for Scrypto SBOR types of package address: package_rdx1phwak2lr7nczzl6rxzvtnjwszmvxqycp9h8pckcmy6uwdcucnjeu0p
// Generated by: https://www.8arms1goal.com/sbor-ez-mode-ez-mode

export const OperatingStatusValue = s.struct({
  enabled: s.number(),
  set_by_admin: s.number(),
});

export const OperatingStatus = s.struct({
  is_contribute_enabled: OperatingStatusValue,
  is_redeem_enabled: OperatingStatusValue,
  is_deposit_enabled: OperatingStatusValue,
  is_withdraw_enabled: OperatingStatusValue,
  is_borrow_enabled: OperatingStatusValue,
  is_repay_enabled: OperatingStatusValue,
  is_liquidate_enabled: OperatingStatusValue,
});

export const CDPUpdatedEvenType = s.enum([
  { variant: "AddCollateral", schema: s.tuple([]) },
  { variant: "RemoveCollateral", schema: s.tuple([]) },
  { variant: "Borrow", schema: s.tuple([]) },
  { variant: "Repay", schema: s.tuple([]) },
  { variant: "Liquidate", schema: s.tuple([]) },
]);

export const LendingPoolUpdatedEventType = s.enum([
  { variant: "DepositState", schema: s.tuple([]) },
  { variant: "LoanState", schema: s.tuple([]) },
  { variant: "CollateralState", schema: s.tuple([]) },
  { variant: "Interest", schema: s.tuple([]) },
  { variant: "Price", schema: s.tuple([]) },
]);

export const CDPUpdatedEvent = s.struct({
  cdp_id: s.nonFungibleLocalId(),
  event_type: CDPUpdatedEvenType,
});

export const MarketConfig = s.struct({
  max_cdp_position: s.number(),
  max_liquidable_value: s.decimal(),
  liquidation_dex_swap_rate: s.decimal(),
});

export const NonFungibleGlobalId = s.struct({
  resource_address: s.address(),
  local_id: s.nonFungibleLocalId(),
});

export const ResourceOrNonFungible = s.enum([
  { variant: "NonFungible", schema: s.tuple([NonFungibleGlobalId]) },
  { variant: "Resource", schema: s.tuple([NonFungibleGlobalId]) },
]);

export const ProofRule = s.enum([
  { variant: "Require", schema: s.tuple([ResourceOrNonFungible]) },
  { variant: "AmountOf", schema: s.tuple([ResourceOrNonFungible]) },
  { variant: "CountOf", schema: s.tuple([ResourceOrNonFungible]) },
  { variant: "AllOf", schema: s.tuple([ResourceOrNonFungible]) },
  { variant: "AnyOf", schema: s.tuple([ResourceOrNonFungible]) },
]);

export const AccessRuleNode = s.enum([
  { variant: "ProofRule", schema: s.tuple([ProofRule]) },
  { variant: "AnyOf", schema: s.tuple([ProofRule]) },
  { variant: "AllOf", schema: s.tuple([ProofRule]) },
]);

export const AccessRule = s.enum([
  { variant: "AllowAll", schema: s.tuple([]) },
  { variant: "DenyAll", schema: s.tuple([]) },
  { variant: "Protected", schema: s.tuple([]) },
]);

export const LendingMarket = s.struct({
  admin_rule: AccessRule,
  cdp_res_manager: s.address(),
  cdp_counter: s.number(),
  liquidator_counter: s.number(),
  market_component_address: s.address(),
  pool_unit_refs: s.map({ key: s.address(), value: s.address() }),
  reverse_pool_unit_refs: s.map({ key: s.address(), value: s.address() }),
  listed_assets: s.array(s.address()),
  pool_states: s.internalAddress(),
  transient_res_manager: s.address(),
  liquidator_badge_manager: s.address(),
  operating_status: OperatingStatus,
  market_config: MarketConfig,
});

export const LendingPoolUpdatedEvent = s.struct({
  pool_res_address: s.address(),
  event_type: LendingPoolUpdatedEventType,
  amount: s.decimal(),
});

export const CDPType = s.enum([{ variant: "Standard", schema: s.tuple([]) }]);

export const CollaterizedDebtPositionData = s.struct({
  key_image_url: s.string(),
  name: s.string(),
  description: s.string(),
  minted_at: s.number(),
  updated_at: s.number(),
  cdp_type: CDPType,
  collaterals: s.map({ key: s.address(), value: s.decimal() }),
  loans: s.map({ key: s.address(), value: s.decimal() }),
  liquidable: s.option(s.decimal()),
});

export type CollaterizedDebtPositionData = s.infer<
  typeof CollaterizedDebtPositionData
>;

export const CDPLiquidable = s.struct({
  cdp_data: CollaterizedDebtPositionData,
  cdp_id: s.nonFungibleLocalId(),
});

export const CDPLiquidableEvent = s.struct({
  cdps: s.array(CDPLiquidable),
});
